[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
build_flags =
    -D CONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=1
    -D CONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER=1
    -D DEBUG_LOG=1

[env:native]
platform = native
build_flags = -std=c++17
test_build_src = false
